### ISSUE TITLE
Permission denied trying to programmatically download pretrained models in Colab

### ISSUE THREAD

**Issue by virtualramblas** [chail/latent-composition#1]
Hi,

I am trying to run the **interactive-masking** notebook in Google Colab, but the cell containing the code to download the pretrained models fails giving the error message in the attached screenshot:
![image](https://user-images.githubusercontent.com/1730182/111882032-2e0dc780-89ab-11eb-8a64-022626c1f58e.png)
Probably you would need to change the permission for the ZIP archive in your Google Drive space?

Best Regards,
Guglielmo

**Comment by chail** [comment]
Hi, it seems like my gdrive is limiting downloads, causing it to fail despite the file being being publicly viewable. I've added a copy at http://people.csail.mit.edu/lrchai/projects/latent-composition/pretrained_models.zip and updated the colabs to try to download from here in case the gdrive download fails (although the download speed from here will be slower compared to gdrive).

**Comment by virtualramblas** [comment]
Hi Lucy,

Thanks for your quick action. By replacing the original gdown download with a wget from the new ZIP archive location, the download is successful and I was able to execute the rest of this Colab notebook. Going to close this issue.

Best Regards,
Guglielmo
