### ISSUE TITLE
Error in colab

### ISSUE THREAD

**Issue by amrzv** [chail/latent-composition#4]
Hi.
Have an `IndexError: list index out of range` when running `interactive-masking.ipynb` notebook in colab with default settings.
![image](https://user-images.githubusercontent.com/36787333/131617019-e86b49ee-3943-4de9-ba55-944307e45317.png)

It fails on `mask_list[-1]`, because it is empty. (it can be seen on image above, no mask right to the car).

**Comment by chail** [comment]
fixed, thanks.
