### ISSUE TITLE
Loading NVIDIA's pretrained StyleGAN2 pickles

### ISSUE THREAD

**Issue by yulonglin** [chail/latent-composition#5]
What's the easiest way to load pickle files of pretrained StyleGAN2 models from NVIDIA? For example those found here:
- https://github.com/NVlabs/stylegan2
- https://github.com/NVlabs/stylegan2-ada-pytorch

We can modify the StyleGAN settings and also the [location of the StyleGAN generator](https://github.com/chail/latent-composition/blob/09ba79f4b0a1642ce4c5ebfa1c3e34644c92770c/networks/stylegan_networks.py#L27). But how should we load the weights [here](https://github.com/chail/latent-composition/blob/09ba79f4b0a1642ce4c5ebfa1c3e34644c92770c/utils/pt_stylegan2.py#L38)? You seem to have reimplemented a `Generator` class so it doesn't seem directly compatible with NVIDIA's original implementations

An example of an NVIDIA StyleGAN2 model: https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/stylegan2-cat-config-f.pkl

**Comment by yulonglin** [comment]
To get it working, I [converted the StyleGAN2 ADA PyTorch official repo into a package](https://github.com/yulonglin/stylegan2-ada-pytorch), pip installed it, then replaced all calls to the generator in `train_sgan_encoder.py` and related files with the official repo's `Generator` class.

**Comment by chail** [comment]
I used the conversion method [here](https://github.com/rosinality/stylegan2-pytorch#convert-weight-from-official-checkpoints) but your method should work too!
