### ISSUE TITLE
VAE experiments

### ISSUE THREAD

**Issue by ruoshiliu** [chail/latent-composition#6]
Hi @chail, thank you for sharing the code! I saw in the code that the option of a VAE encoder is implemented but didn't seem to find any relevant experiments or results in the paper. Would it possible to share some insights into what the results would look like if the inverted latent code is variational? Does the distribution produced by the VAE capture any realistic diversity? Thanks in advance!

**Comment by chail** [comment]
I implemented this but didn't end up using it for the paper because the standard deviation parameter quite quickly becomes zero as the mask area becomes smaller; so I think more could be done to regularize it so that the generated samples are more diverse.
