### ISSUE TITLE
how to create dataset

### ISSUE THREAD

**Issue by kleinar** [chail/latent-composition#8]
Hello. I'm interested in the composition model. I want to train a model to realistically transfer an object from one image to another. Essentially the same as composing parts of the face. How can I prepare a dataset for training? In what format should they be?

**Comment by chail** [comment]
Thanks for the inquiry! The model here is trained using synthetic images, which are generated via latent noises. But if you want to also train on reference images, probably you can replace the `z_data` dataset [here](https://github.com/chail/latent-composition/blob/main/utils/training_utils.py#L69-L70) with an instance of `torchvision.datasets.ImageFolder` ([docs](https://pytorch.org/vision/0.16/generated/torchvision.datasets.ImageFolder.html#torchvision.datasets.ImageFolder)).
